name: Build and Deploy Server

on:
  workflow_call:
    outputs:
      IMAGE_TAG:
        description: 'The tag of the built image'
        value: ${{ steps.set-output.outputs.image_tag }}

env:
  COMMIT_TAG: ${{ github.sha }}

jobs:
  build-server:
    name: Build Server Image
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        id: login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push server image to dockerhub
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: iadebisi/multi-server:${{ env.COMMIT_TAG }},iadebisi/multi-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set output image tag
        id: set-output
        run: echo "image_tag=${{ env.COMMIT_TAG }}" >> $GITHUB_OUTPUT
