name: Build and Push Client

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
    outputs:
      IMAGE_TAG:
        description: 'The tag of the built image'
        value: ${{ jobs.build.outputs.image_tag }}

env:
  COMMIT_TAG: ${{ github.sha }}

jobs:
  build-client:
    name: Build Client Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-output.outputs.image_tag }}
    environment: dev
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        id: login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to dockerhub
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: iadebisi/multi-client:${{ env.COMMIT_TAG }},iadebisi/multi-client:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set output image tag
        id: set-output
        run: echo "image_tag=${{ env.COMMIT_TAG }}" >> $GITHUB_OUTPUT
